clinic/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('reception/', include('reception.urls',namespace='reception')),
    path('take_turn/', include('take_turn.urls',namespace='turn')),
    path('accounts/', include('account.urls',namespace='account')),

    path('da/', include('dashboard.urls', namespace='dashboard')),
    path('', include('mainpage.urls', namespace='main')),

]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mainpage/urls.py
from django.urls import  path
from . import views
app_name = 'main'
urlpatterns = [

    path('', views.Home, name= 'home'),
    path('search/',views.searchb_us,name='search'),
    path('report/',views.pationt_list, name='pationt_list'),
    path('surgery_list/',views.surgery_list, name='surgery_list'),
    path('Turn_list/',views.Turn_list, name='Turn_list'),
    path('create',views.creatFile, name='creatFile'),
    path('calender',views.Calender, name='Calender'),
    path('<int:id>/', views.patient_file,name='patient_file'),
    path('p_download', views.download, name="p_download"),
    path('s_download', views.download2, name="s_download"),
    path('t_download', views.download3, name="t_download"),
    path('res_download', views.download4, name="p_download4")


]

reception/urls.py
from django.urls import  path
from . import views
app_name = 'reception'
urlpatterns = [
    path('List', views.list_of_rec, name='listRec'),
    path('reToSurgery/', views.reToSurgery, name= 'reToSurgery'),
    path('<int:id>', views.reception_form, name= 'reception'),
    path('<int:id>/<int:EntranceCode>', views.recption_detail, name= 'receptionDetaile'),
    path('surgery/<int:id>', views.Refer_Surgery, name= 'Refer_Surgery'),
]

reception/models.py
from django.db import models
from mainpage.models import Reception,Patient
from django.contrib.auth.models import User
from jalali_date import date2jalali
# Create your models here.

class PaymentReceipt(models.Model):
    Reception=models.ForeignKey(Reception, related_name='paymentReception', on_delete=models.CASCADE,verbose_name='پذیرش')
    Device = models.CharField(max_length = 10,verbose_name="دستگاه")
    Cashier = models.ForeignKey(User,related_name='Cashier', on_delete=models.CASCADE,default= '1', verbose_name="صندوقدار")
    mobile = models.CharField(max_length=13, verbose_name="تلفن همراه")
    Paid = models.IntegerField(verbose_name="مبلغ پرداخت شده")
    def __str__(self):
        return '{} {}'.format(self.Cashier, self.Reception)

    class Meta:
        verbose_name = "رسید صندوق"
        verbose_name_plural = "رسید های صندوق"

class refer_to_surgery(models.Model):
    Patient=models.ForeignKey(Patient, related_name='surgerypatuent', on_delete=models.CASCADE,verbose_name='بيمار')
    date_time = models.DateField(auto_now_add=False,auto_now=False, verbose_name="تاریخ")
    name = models.CharField(max_length = 200,verbose_name="عنوان عمل جراحي")
    name_Doc = models.CharField(max_length = 50,verbose_name="نام پزشك معالج")
    patient_history = models.FileField(upload_to='patient_history/%Y/%m/%d', null=True, blank=True,verbose_name='شرح حال')
    Medical_innocence= models.FileField(upload_to='Medical_innocence/%Y/%m/%d', null=True, blank=True,verbose_name='برائت نامه')
    def __str__(self):
        return '{}- Doctor:{}'.format(self.Patient, self.name_Doc)
    class Meta:
        verbose_name = "ارجاع به جراحي"
        verbose_name_plural = "ارجاع ها به جراحي"
    def get_jalali_date(self):
        return date2jalali(self.date_time)

reception/forms.py
from django import forms
from jalali_date.fields import JalaliDateField,SplitJalaliDateTimeField
from jalali_date.widgets import AdminJalaliDateWidget, AdminSplitJalaliDateTime
from django.contrib.admin.widgets import AdminDateWidget
from django.forms.fields import DateField
from .models import PaymentReceipt,refer_to_surgery
from mainpage.models import Reception
class paymentEditForm(forms.Form):
    price = forms.CharField(label='ثبت مبلغ جدید')
    state = forms.CharField(widget=forms.HiddenInput(), initial="1")
    def __init__(self, *args, **kwargs):
        super(paymentEditForm,self).__init__(*args, **kwargs)
        self.fields['price'].widget.attrs['class'] = 'form-control'

class ReceptionEditForm(forms.ModelForm):
    services = forms.CharField(label='خدمات گرفته شد')
    # diagnisis = forms.CharField(label='تشخیص ها')
    class Meta:
        model = Reception
        fields = ('TurnCode',
         'date','Referrer','Description')
    def __init__(self, *args, **kwargs):
        super(ReceptionEditForm,self).__init__(*args, **kwargs)
        self.fields['date'] = SplitJalaliDateTimeField(label=('تاریخ نوبت'),
                     # required, for decompress DatetimeField to JalaliDateField and JalaliTimeField
                )
        self.fields['Referrer'].required = False
        self.fields['services'].widget.attrs['class'] = 'form-control'
        # self.fields['diagnisis'].widget.attrs['class'] = 'form-control'
        self.fields['TurnCode'].widget.attrs['class'] = 'form-control'
        self.fields['date'].widget.attrs['class'] = 'form-control'
        self.fields['Referrer'].widget.attrs['class'] = 'form-control'
        self.fields['Description'].widget.attrs['class'] = 'form-control'

class surgeryEditForm(forms.ModelForm):
    class Meta:
        model = refer_to_surgery
        fields = ('name','name_Doc','date_time','patient_history','Medical_innocence')
    def __init__(self, *args, **kwargs):
        super(surgeryEditForm,self).__init__(*args, **kwargs)

        self.fields['date_time'] = JalaliDateField(label=('تاريخ جراحي'), # date format is  "yyyy-mm-dd"
            widget=AdminJalaliDateWidget # optional, to use default datepicker
        )
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name_Doc'].widget.attrs['class'] = 'form-control'
        self.fields['date_time'].widget.attrs['class'] = 'form-control'
        self.fields['patient_history'].widget.attrs['class'] = 'form-control'
        self.fields['Medical_innocence'].widget.attrs['class'] = 'form-control'
class refToSurgeryEditForm(forms.ModelForm):
    NationalCode = forms.CharField(label='کد ملی')
    class Meta:
        model = refer_to_surgery
        fields = ('name','name_Doc','date_time','patient_history','Medical_innocence')
    def __init__(self, *args, **kwargs):
        super(refToSurgeryEditForm,self).__init__(*args, **kwargs)
        self.fields['NationalCode'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name_Doc'].widget.attrs['class'] = 'form-control'
        self.fields['date_time'].widget.attrs['class'] = 'form-control'
        self.fields['patient_history'].widget.attrs['class'] = 'form-control'
        self.fields['Medical_innocence'].widget.attrs['class'] = 'form-control'
        self.fields['date_time'] = JalaliDateField(label=('تاريخ جراحي'), # date format is  "yyyy-mm-dd"
            widget=AdminJalaliDateWidget # optional, to use default datepicker
        )


class PayReceiptEditForm(forms.ModelForm):
    state = forms.CharField(widget=forms.HiddenInput(), initial="2")
    class Meta:
        model = PaymentReceipt
        fields = ('Device', 'mobile', 'Paid')
    def __init__(self, *args, **kwargs):
        super(PayReceiptEditForm,self).__init__(*args, **kwargs)
        self.fields['Device'].widget.attrs['class'] = 'form-control'
        self.fields['mobile'].widget.attrs['class'] = 'form-control'
        self.fields['Paid'].widget.attrs['class'] = 'form-control'

reception/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth.models import User
from .forms import ReceptionEditForm,paymentEditForm,PayReceiptEditForm,surgeryEditForm,refToSurgeryEditForm
from mainpage.models import Patient,Take_Turn,Services,Reception,PatientItem,Diagnosis,PatientDiagnosis,day_of
from .models import PaymentReceipt,refer_to_surgery
from django.contrib.auth.decorators import login_required
from jalali_date import date2jalali
from datetime import date as D
from datetime import datetime
from account.check_user import chech_profile
# Create your views here.
@login_required
def reception_form(request, id):
    user = request.user
    x = chech_profile(user, 12)
    if x == True:
        patient = get_object_or_404(Patient,id=id)
        mess = None
        alert = None
        if request.method == 'POST':
                reception = ReceptionEditForm(request.POST)
                if reception.is_valid():
                    cd =reception.cleaned_data
                    all_re = Reception.objects.all()
                    count = len(all_re)

                    entranceCode = count+1

                    try:
                        Rec=Reception.objects.create(Patient=patient,user=user,EntranceCode=entranceCode,TurnCode =cd['TurnCode'], date=cd['date'],Referrer=cd['Referrer'],Description=cd['Description'])
                        ListSercice =eval(cd['services'])
                        # ListD =eval(cd['diagnisis'])
                        L_ser = []
                        if type(ListSercice) == int:
                            ListSercice =(ListSercice,)
                        # if type(ListD) == int:
                            # ListD =(ListD,)
                        for i in ListSercice:
                            x=get_object_or_404(Services, id=i)
                            PatientItem.objects.create(Reception=Rec,Services=x,price=x.Price)
                            L_ser.append(x.Service)
                        # for i in ListD:
                            # y=get_object_or_404(Diagnosis, id=i)
                            # PatientDiagnosis.objects.create(reception=Rec,diagnisis=y)

                        mess = "پذیرش بیمار انجام شد." + " خدمات: " + str(L_ser).replace('[','').replace(']','').replace("'",'')
                    except:
                        alert = "پذیرش ثبت نشد ورودی ها نامعتبر هستند "
                        Rec.delete()
                else:
                    mess="ورودی ها نامعتبر هستند."
        turn = Take_Turn.objects.filter(Patient=patient)
        try:
            x =turn[turn.count()-1]
        except:
            x = None
        service = Services.objects.all()
        diagnosis = Diagnosis.objects.all()
        list_day = day_of.objects.all()
        form = ReceptionEditForm()
        today = date2jalali(D.today())
        time_now = datetime.now().strftime('%H:%M')
        return render(request, "reception/reception.html",{'form':form,'patient':patient,'turn':x,'service':service,'diagnosis':diagnosis,'now':time_now,'mess':mess,'alert':alert,'lsit_day':list_day,'today':today})
    else:
        return render(request, 'main/error.html',{'mess':'دسترسی ثبت پذیرش برای شما فعال نشده است.'})


@login_required
def recption_detail(request,id ,EntranceCode ):

    user = request.user
    x = chech_profile(user, 12)
    if x == True:
        this = get_object_or_404(Reception, id = id,EntranceCode=EntranceCode)
        if request.method == 'POST':

            if request.POST.get('state') == '1':
                price = paymentEditForm(request.POST)
                if price.is_valid():
                    this.Payable = price.cleaned_data['price']
                    this.save()
                else:
                    pass
            elif request.POST.get('state') == '2':
                payform = PayReceiptEditForm(request.POST)
                if payform.is_valid():
                    cd=payform.cleaned_data
                    pay =PaymentReceipt.objects.create(Reception=this,Device=cd['Device'],mobile =cd['mobile'], Paid=cd['Paid'])
                    pay.Cashier=request.user
                    pay.save()
                else:
                    pass
        pform =paymentEditForm()
        payform =PayReceiptEditForm()
        this_service =PatientItem.objects.filter(Reception=this)
        diagnisis =PatientDiagnosis.objects.filter(reception=this)
        paid = PaymentReceipt.objects.filter(Reception=this)
        return render(request,'reception/detail.html',{'this':this,'this_service':this_service,'pform':pform,'payform':payform,'paid':paid,'diagnisis':diagnisis})
    else:
        return render(request, 'main/error.html',{'mess':'دسترسی ثبت پذیرش برای شما فعال نشده است.'})

@login_required
def list_of_rec(request):
    user = request.user
    x = chech_profile(user, 11)
    if x == True:
        reception =Reception.objects.all()
        return render(request,'reception/rec_list.html',{'Reception':reception})
    else:
        return render(request, 'main/error.html',{'mess':'دسترسی به لیست پذیرش برای شما فعال نشده است.'})


def Refer_Surgery(request, id):
    user = request.user
    x = chech_profile(user, 14)
    if x == True:
        patient = get_object_or_404(Patient,id=id)
        if request.method == 'POST':
            surgeryform = surgeryEditForm(data=request.POST,files=request.FILES)
            if surgeryform.is_valid():
                cd= surgeryform.cleaned_data
                name =cd['name']
                Doc = cd['name_Doc']
                date = cd['date_time']
                try:
                    history =request.FILES['patient_history']
                except:
                    history = None
                try:
                    innocence =request.FILES['Medical_innocence']
                except:
                    innocence = None



                refer_to_surgery.objects.create(Patient=patient, name=name, name_Doc=Doc, date_time=date,patient_history=history, Medical_innocence=innocence)


                return redirect(patient)

        list_day = day_of.objects.all()
        form = ReceptionEditForm()
        today = date2jalali(D.today())
        form =surgeryEditForm()
        return render(request,'reception/surgery.html',{'patient':patient,'form':form,'lsit_day':list_day,'today':today} )
    else:
        return render(request, 'main/error.html',{'mess':'دسترسی ارجاع به جراحی برای اکانت شما فعال نشده است.'})
@login_required
def reToSurgery (request):

    user = request.user
    x = chech_profile(user, 14)
    if x == True:

        if request.method == 'POST':
            surgeryform = surgeryEditForm(data=request.POST, files=request.FILES)
            if surgeryform.is_valid():
                cd= surgeryform.cleaned_data
                try:
                    NationalCode = request.POST['NationalCode']
                    patient = get_object_or_404(Patient,NationalCode=NationalCode)

                    name = cd['name']
                    Doc = cd['name_Doc']
                    date = cd['date_time']
                    try:
                        history =request.FILES['patient_history']
                    except:
                        history = None
                    try:
                        innocence =request.FILES['Medical_innocence']
                    except:
                        innocence = None


                    refer_to_surgery.objects.create(Patient=patient, name=name, name_Doc=Doc, date_time=date,patient_history=history, Medical_innocence=innocence)


                    return redirect(patient)
                except:
                     return render(request, 'main/error.html',{'mess':'برای کد ملی وارد شده پرونده فعالی وجود ندارد'})
            else:
                return render(request, 'main/error.html',{'mess':'ورودی ها نامعتبر یا فاقد مقدار هستند.'})

        list_day = day_of.objects.all()
        form = ReceptionEditForm()
        today = date2jalali(D.today())
        form =refToSurgeryEditForm()
        return render(request,'reception/surgeryform.html',{'form':form,'lsit_day':list_day,'today':today} )
    else:
        return render(request, 'main/error.html',{'mess':'دسترسی ارجاع به جراحی برای اکانت شما فعال نشده است.'})

reception/templates/reception/surgery.html
{% extends "main/layout.html" %}
{% load static %}
{% load jalali_tags %}
{% block styles %}

<link href="{% static 'css/Mh1PersianDatePicker.css' %}" rel="stylesheet" />
<link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
{% endblock %}
{% block content %}
<style media="screen">
.needs-validation textarea{
  height : 75px;


}
#id_date_time_0{
  display: block;
  width: 100%;
  height: calc(2.25rem + 2px);
  padding: 0.375rem 0.75rem;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5;
  color: #495057;
  background-color: #fff;
  background-clip: padding-box;
  border: 1px solid #ced4da;
  border-radius: 0.25rem;
  transition: border-color 0.15s ease-in-out,box-shadow 0.15s ease-in-out;
}
#id_date_time_1{
  display: block;
  width: 100%;
  height: calc(2.25rem + 2px);
  padding: 0.375rem 0.75rem;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5;
  color: #495057;
  background-color: #fff;
  background-clip: padding-box;
  border: 1px solid #ced4da;
  border-radius: 0.25rem;
  transition: border-color 0.15s ease-in-out,box-shadow 0.15s ease-in-out;
}
</style>
<div class="app-main__inner">
    <div class="main-card mb-3 card">
<div class="card-body"><h5 class="card-title">مشخصات <a href="{{patient.get_absolute_url}}"><button class="active btn btn-focus">پرونده </button></a></h5>
<div class="row">
<div class="col">
    <ul class="nav flex-column">

        <li class="nav-item"><a href="javascript:void(0);" class="nav-link">نام

            {% if patient.p_name %}
              <div class="ml-auto badge badge-success">{{patient.p_name}}</div>
            {% else %}
            <div class="ml-auto badge badge-danger">{{patient.p_name}}</div>
            {% endif %}
        </a></li>
        <li class="nav-item"><a href="javascript:void(0);" class="nav-link">نام خانوادگي

            {% if patient.last_name %}
              <div class="ml-auto badge badge-success">{{patient.last_name}}</div>
            {% else %}
            <div class="ml-auto badge badge-danger">{{patient.last_name}}</div>
            {% endif %}
        </a></li>
        <li class="nav-item"><a href="javascript:void(0);" class="nav-link">شماره تلفن

            {% if patient.mobile %}
              <div class="ml-auto badge badge-success">{{patient.mobile}}</div>
            {% else %}
            <div class="ml-auto badge badge-danger">{{patient.mobile}}</div>
            {% endif %}
        </a></li>
    </ul>
</div>
<div class="col">
    <ul class="nav flex-column">
      <li class="nav-item"><a href="javascript:void(0);" class="nav-link">تلفن ثابت
        {% if patient.land_line_phone %}
          <div class="ml-auto badge badge-success">{{patient.land_line_phone}}</div>
        {% else %}
        <div class="ml-auto badge badge-danger">{{patient.land_line_phone}}</div>
        {% endif %}

      </a></li>
      <li class="nav-item"><a href="javascript:void(0);" class="nav-link">سن

          {% if patient.age %}
            <div class="ml-auto badge badge-success">{{patient.age}}</div>
          {% else %}
          <div class="ml-auto badge badge-danger">{{patient.age}}</div>
          {% endif %}
      </a></li>
      <li class="nav-item"><a href="javascript:void(0);" class="nav-link">جنسيت
          {% if patient.Gender == 1 %}<div class="ml-auto badge badge-success"> مرد </div>{% elif patient.Gender == 0  %} <div class="ml-auto badge badge-success"> زن</div> {% else %} <div class="ml-auto badge badge-danger">نا مشخص</div> {% endif %}
      </a></li>

    </ul>
</div>
</div>

</div>
</div>
  <div class="main-card mb-3 card">
      <div class="card-body">

            <h5 class="card-title">ثبت جراحی</h5>
            <form class="needs-validation" action="{% url 'reception:Refer_Surgery' patient.id %}" method="post" enctype="multipart/form-data">

              {% csrf_token %}
              <div class="form-row">
                  <div class="col-md-4 mb-3">
                      <label for="validationCustom01">عنوان عمل*</label>
                      {{form.name}}
                      <div class="valid-feedback">
                          Looks good!
                      </div>
                  </div>
                  <div class="col-md-4 mb-3">
                      <label for="validationCustom02">نام پزشک*</label>
                      {{form.name_Doc}}
                      <div class="valid-feedback">
                          Looks good!
                      </div>
                  </div>

                  <div class="col-md-4 mb-3">
                      <label for="validationCustomUsername">شرح حال*</label>
                      <div class="input-group">
                          <div class="input-group-prepend">
                              <span class="input-group-text" id="inputGroupPrepend"></span>
                          </div>
                        {{form.patient_history}}
                          <div class="invalid-feedback">

                          </div>
                      </div>
                  </div>
              </div>
              <div class="form-row">
                  <div class="col-md-6 mb-3">
                      <label for="validationCustom03">برائت نامه*</label>
                      {{form.Medical_innocence}}
                      <div class="invalid-feedback">
                          Please provide a valid part.
                      </div>
                  </div>
                  <div class="col-md-3 mb-3">
                      <label for="validationCustom04">تاريخ *</label>
                      {{form.date_time}}
                      <div class="invalid-feedback">
                          Please provide a valid state.
                      </div>
                  </div>

              </div>
            <p>{{ request.user.date_joined|to_jalali:' تاریخ: 14%y/%m/%d_ ساعت: %H:%M' }}</p>
              <button class="btn btn-primary" type="submit">ثبت ارجاع</button>
          </form>

      </div>
  </div>

</div>

<script src="{% static 'js/Mh1PersianDatePicker.js' %}"></script>
<script type="text/javascript">
    window.holidays = [];
</script>
{% for i in lsit_day %}
<script type="text/javascript">
  window.holidays.push('{{i.get_jalali_date}}')
</script>
{% endfor %}

<script>
    //script1
    var inputs = document.querySelectorAll('#id_date_time');

    for (i = 0; i < inputs.length; i++) {
        (function (i) {
          inputs[i].addEventListener('click', function () {
                Mh1PersianDatePicker.Show(this, '{{today}}', window.holidays);
            });
        })(i);
    }
    //script1
</script>
<script type="text/javascript">id_status
  document.getElementById('id_searchtxt').placeholder ='جستجو';
  document.getElementById('id_status').value = '1';
</script>

{% endblock %}

reception/templates/reception/surgery1.html
{% extends "main/base.html" %}
{% load static %}
{% block custom_css %}
<link href="{% static 'css/surgery.css' %}?v=6" rel="stylesheet">
<link href="{% static 'css/Mh1PersianDatePicker.css' %}" rel="stylesheet" />
{% endblock %}
{% block title %}p_login{% endblock %}
{% block content %}
<div class="surgery-box">
  <div class="surgery_form_head">
    <h2>فرم ارجاع به جراحي</h2>
  </div>
  <table class="Form-Table">

    <thead>
      <tr>
        <th>نام: {{patient.p_name}}</th>
        <th>نام خانوادگي: {{patient.last_name}}</th>
        <th>شماره ملي: {{patient.NationalCode}}</th>
      </tr>
    </thead>
    <thead>
      <tr>
        <th>شماره همراه: {{patient.mobile}}</th>
        <th>جنسيت: {% if patient.Gender == 1 %}مرد {% elif patient.Gender == 0  %} زن {% else %} نامشخص {% endif %}</th>
        <th>سن: {{patient.age}}</th>
      </tr>
    </thead>
    <thead>
      <tr>
        <th>تلفن ثابت: {{patient.land_line_phone}}</th>
      </tr>
    </thead>
    <form class="" action="{% url 'reception:Refer_Surgery' patient.NationalCode %}" method="post" enctype="multipart/form-data">
    <tbody>
      <tr>
        <td>{{form.date_time}}*</td>
        <td>{{form.name}}*</td>
        <td>{{form.name_Doc}}*</td>
      </tr>
    </tbody>
    <thead>
      <tr>
        <th>{{form.patient_history.label}}</th>
        <th>{{form.Medical_innocence.label}}</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{form.patient_history}}</td>
        <td>{{form.Medical_innocence}}</td>
      </tr>
    </tbody>
    <thead>
      <tr>
              {% csrf_token %}
        <th><button class="ebtn" type="submit" name="button">ثبت</button></th>
      </tr>
    </thead>
    </form>
  </table>
</div>

<script src="{% static 'js/Mh1PersianDatePicker.js' %}"></script>
<script type="text/javascript">
    window.holidays = [];
</script>
{% for i in lsit_day %}
<script type="text/javascript">
  window.holidays.push('{{i.get_jalali_date}}')
</script>
{% endfor %}

<script>
    //script1
    var inputs = document.querySelectorAll('#id_date_time');

    for (i = 0; i < inputs.length; i++) {
        (function (i) {
          inputs[i].addEventListener('click', function () {
                Mh1PersianDatePicker.Show(this, '{{today}}', window.holidays);
            });
        })(i);
    }
    //script1
</script>
<script type="text/javascript">
  document.getElementById('id_name').placeholder ='عنوان عمل جراحي';
  document.getElementById('id_name_Doc').placeholder ='نام پزشك';
  document.getElementById('id_date_time').placeholder ="تاريخ عمل 01-01-1400";

</script>
{% endblock %}

reception/templates/reception/surgeryform.html
{% extends "main/layout.html" %}
{% load static %}
{% load jalali_tags %}
{% block styles %}

<link href="{% static 'css/Mh1PersianDatePicker.css' %}" rel="stylesheet" />

{% endblock %}
{% block content %}
<style media="screen">
.jalali_date-date{
    display: block;
    width: 100%;
    height: calc(2.25rem + 2px);
    padding: 0.375rem 0.75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: 0.25rem;
    transition: border-color 0.15s ease-in-out,box-shadow 0.15s ease-in-out;
}
</style>
                    <div class="app-main__inner">
                      <div class="main-card mb-3 card">
                          <div class="card-body">

                                <h5 class="card-title">ارجاع به جراحي</h5>
                                <form class="needs-validation" action="{% url 'reception:reToSurgery'%}" method="post" enctype="multipart/form-data" novalidate>

                                  {% csrf_token %}
                                  <div class="form-row">

                                      <div class="col-md-4 mb-3">
                                          <label for="validationCustom01">كد ملي*</label>
                                          {{form.NationalCode}}
                                          <div class="valid-feedback">
                                              Looks good!
                                          </div>
                                      </div>
                                      <div class="col-md-4 mb-3">
                                          <label for="validationCustom02">تاريخ جراحي*</label>
                                          {{form.date_time}}
                                          <div class="valid-feedback">
                                              Looks good!
                                          </div>
                                      </div>

                                      <div class="col-md-4 mb-3">
                                          <label for="validationCustomUsername">نام عمل جراحي*</label>
                                          <div class="input-group">
                                              <div class="input-group-prepend">
                                                  <span class="input-group-text" id="inputGroupPrepend"></span>
                                              </div>
                                            {{form.name}}
                                              <div class="invalid-feedback">

                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <div class="form-row">
                                      <div class="col-md-6 mb-3">
                                          <label for="validationCustom03">نام پزشك *</label>
                                          {{form.name_Doc}}
                                          <div class="invalid-feedback">
                                              Please provide a valid part.
                                          </div>
                                      </div>
                                      <div class="col-md-3 mb-3">
                                          <label for="validationCustom04">شرح حال</label>
                                          {{form.patient_history}}
                                          <div class="invalid-feedback">
                                              Please provide a valid state.
                                          </div>
                                      </div>
                                      <div class="col-md-3 mb-3">
                                          <label for="validationCustom05">برائت نامه</label>
                                          {{form.Medical_innocence}}
                                          <div class="invalid-feedback">
                                              Please!
                                          </div>
                                      </div>
                                  </div>
                                <p>{{ request.user.date_joined|to_jalali:' تاریخ: 14%y/%m/%d_ ساعت: %H:%M' }}</p>
                                  <button class="btn btn-primary" type="submit">ثبت ارجاع</button>
                              </form>

                          </div>
                      </div>
  <script src="{% static 'js/Mh1PersianDatePicker.js' %}"></script>
  <script type="text/javascript">
      window.holidays = [];
  </script>
  {% for i in lsit_day %}
  <script type="text/javascript">
    window.holidays.push('{{i.get_jalali_date}}')
  </script>
  {% endfor %}

  <script>
      //script1
      var inputs = document.querySelectorAll('#id_date_time');

      for (i = 0; i < inputs.length; i++) {
          (function (i) {
            inputs[i].addEventListener('click', function () {
                  Mh1PersianDatePicker.Show(this, '{{today}}', window.holidays);
              });
          })(i);
      }
      //script1
  </script>
  <script type="text/javascript">
    document.getElementById('id_NationalCode').placeholder ='کدملی';
    document.getElementById('id_name').placeholder ='عنوان عمل جراحي';
    document.getElementById('id_name_Doc').placeholder ='نام پزشك';
    document.getElementById('id_date_time').placeholder ="تاريخ عمل 01-01-1400";

  </script>
{% endblock %}