account/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views

app_name = 'account'

urlpatterns = [

    path('login/', csrf_exempt(views.user_login), name='login'),
    path('profile/', views.profile, name='profile'),
    path('logout',views.logoutuser, name='logoutuser')
]

clinic/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('reception/', include('reception.urls',namespace='reception')),
    path('take_turn/', include('take_turn.urls',namespace='turn')),
    path('accounts/', include('account.urls',namespace='account')),

    path('da/', include('dashboard.urls', namespace='dashboard')),
    path('', include('mainpage.urls', namespace='main')),

]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mainpage/urls.py
from django.urls import  path
from . import views
app_name = 'main'
urlpatterns = [

    path('', views.Home, name= 'home'),
    path('search/',views.searchb_us,name='search'),
    path('report/',views.pationt_list, name='pationt_list'),
    path('surgery_list/',views.surgery_list, name='surgery_list'),
    path('Turn_list/',views.Turn_list, name='Turn_list'),
    path('create',views.creatFile, name='creatFile'),
    path('calender',views.Calender, name='Calender'),
    path('<int:id>/', views.patient_file,name='patient_file'),
    path('p_download', views.download, name="p_download"),
    path('s_download', views.download2, name="s_download"),
    path('t_download', views.download3, name="t_download"),
    path('res_download', views.download4, name="p_download4")


]

reception/urls.py
from django.urls import  path
from . import views
app_name = 'reception'
urlpatterns = [
    path('List', views.list_of_rec, name='listRec'),
    path('reToSurgery/', views.reToSurgery, name= 'reToSurgery'),
    path('<int:id>', views.reception_form, name= 'reception'),
    path('<int:id>/<int:EntranceCode>', views.recption_detail, name= 'receptionDetaile'),
    path('surgery/<int:id>', views.Refer_Surgery, name= 'Refer_Surgery'),
]

take_turn/urls.py
from django.urls import  path
from . import views
app_name = 'turn'
urlpatterns = [
    path('', views.take_turn, name= 'take_turn'),
    path('<int:id>', views.take_turn_s, name= 'take_turn_s'),
    path('del/<int:id>', views.delete_turn, name= 'delete_turn'),
    path('delh/<int:id>', views.delete_turn_h, name= 'delete_turn_h'),

]

mainpage/forms.py
from django import forms
from .models import Patient,day_of
from jalali_date.fields import JalaliDateField
from jalali_date.widgets import AdminJalaliDateWidget, AdminSplitJalaliDateTime
class Searchbox (forms.Form):
    searchtxt=forms.CharField (max_length=100, widget=forms.TextInput(attrs={'class':'search-input', 'placeholder':"جستجوی پرونده" }))
class patientEditForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ('NationalCode', 'p_name', 'last_name', 'mobile','land_line_phone','age','Gender')
    def __init__(self, *args, **kwargs):
        super(patientEditForm,self).__init__(*args, **kwargs)
        self.fields['NationalCode'].widget.attrs['class'] = 'form-control'
        self.fields['p_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['mobile'].widget.attrs['class'] = 'form-control'
        self.fields['land_line_phone'].widget.attrs['class'] = 'form-control'
        self.fields['age'].widget.attrs['class'] = 'form-control'
        self.fields['Gender'].widget.attrs['class'] = 'form-control'
CHOICE_LIST = [
    ('', 'جنسیت'), # replace the value '----' with whatever you want, it won't matter
    (0, 'زن'),
    (1, 'مرد')
]
class patientTotalForm(forms.ModelForm):
    Gender=forms.ChoiceField(choices=CHOICE_LIST, required=False)
    class Meta:
        model = Patient
        fields = ( 'NationalCode','p_name', 'last_name', 'mobile','land_line_phone','age')
    def __init__(self, *args, **kwargs):
        super(patientTotalForm,self).__init__(*args, **kwargs)
        self.fields['Gender'].empty_label = "(Select here)"
        self.fields['Gender'].widget.attrs['class'] = 'siavash'

class day_ofEditForm(forms.ModelForm):
    class Meta:
        model = day_of
        fields = ('date_time','Description')
    def __init__(self, *args, **kwargs):
        super(day_ofEditForm,self).__init__(*args, **kwargs)
        self.fields['date_time'] = JalaliDateField(label=('تاریخ'), # date format is  "yyyy-mm-dd"
            widget=AdminJalaliDateWidget
           # optional, to use default datepicker
        )
        self.fields['date_time'].widget.attrs['class'] = 'form-control'
        self.fields['Description'].widget.attrs['class'] = 'form-control'
class Filter_form(forms.Form):
    from_date = forms.DateTimeField()
    to_date = forms.DateTimeField()
    def __init__(self, *args, **kwargs):
        super(Filter_form,self).__init__(*args, **kwargs)
        self.fields['from_date'] = JalaliDateField(label=('از تاریخ'), # date format is  "yyyy-mm-dd"
            widget=AdminJalaliDateWidget
           # optional, to use default datepicker
        )
        self.fields['to_date'] = JalaliDateField(label=("تا تاریخ"),  # date format is  "yyyy-mm-dd"
            widget=AdminJalaliDateWidget
           # optional, to use default datepicker
        )

mainpage/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import  Patient, Take_Turn,Services,Reception,day_of
from reception.models import refer_to_surgery
from .forms import patientEditForm, Searchbox, patientTotalForm,day_ofEditForm,Filter_form
from datetime import datetime,date, timedelta,timezone
import pytz
from jalali_date import date2jalali
from account.check_user import chech_profile
from django.db.models import Q
from django.http import HttpResponse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
import django_excel as excel
from pyexcel_xlsx import save_data
from persiantools.jdatetime import JalaliDate
import datetime as DATE
#import datetime
# Create your views here.

@login_required
def Home (request):
    now=datetime.now()
    tz = pytz.timezone('Asia/Tehran')
    xc=tz.localize(datetime(now.year, now.month, now.day))

    x =Take_Turn.objects.filter(date_time__date=xc)

    return render(request, "main/home.html",{'turn':x})
@login_required
def patient_file(request, id):
    try:
        patient = get_object_or_404(Patient, id=id)
    except:
        patient = get_object_or_404(Patient, pk=id)
    if request.method == 'POST':

        if request.POST.get("NationalCode") != None:
            patient.NationalCode = request.POST.get("NationalCode")
        if request.POST.get('p_name') != None:
            patient.p_name = request.POST.get('p_name')
        if request.POST.get('last_name') != None:
            patient.last_name=request.POST.get('last_name')
        if request.POST.get('mobile') != None:
            patient.mobile=request.POST.get('mobile')
        if request.POST.get('land_line_phone') != None:
            patient.land_line_phone=request.POST.get('land_line_phone')
        if request.POST.get('age') != None and request.POST.get('age') != '':
            patient.age=request.POST.get('age')
        if request.POST.get('Gender') != None and request.POST.get('Gender') != '':
            patient.Gender=request.POST.get('Gender')
        patient.save()
        return redirect(patient)


    else:
        active_turn = []
        deactive_turn = []
        tz = pytz.timezone('Asia/Tehran')
        this_p_turn = Take_Turn.objects.filter(Patient=patient)

        for i in this_p_turn:
            if tz.localize(datetime.now())> i.date_time:
                deactive_turn.append(i)
            else:
                active_turn.append(i)
        reception =Reception.objects.filter(Patient=patient)
        patient_surgery=refer_to_surgery.objects.filter(Patient=patient)
        patientedit = patientEditForm(instance=patient)
        return render(request,'main/detail.html',{'patient': patient,'patientedit':patientedit,'deactive_turn':deactive_turn,'active_turn':active_turn,'reception':reception,'surgery':patient_surgery})
@login_required
def creatFile(request):
    user = request.user
    x = chech_profile(user, 13)
    if x == True:
        if request.method == 'POST':
            form = patientTotalForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                x=Patient.objects.create(NationalCode=cd['NationalCode'],
                p_name=cd['p_name'],
                last_name=cd['last_name'],
                mobile=cd['mobile'],
                land_line_phone=cd['land_line_phone'],
                age=cd['age'],
                Gender=cd['Gender'],
                )

                return redirect(x)
        form =patientTotalForm()
        return render(request,'main/create.html',{'form':form })
    else:
        return render(request, 'main/error.html',{'mess':'دسترسی ایجاد پرونده برای شما فعال نشده است.'})


def searchb_us (request):
    if request.method == 'POST':
        form = Searchbox(request.POST)
        if request.POST.get('status') == '1':
            if form.is_valid():

                text =form.cleaned_data['searchtxt']
                patient = Patient.objects.all()
                q1 = patient.filter(Q(p_name__icontains=text))
                q2 = patient.filter(Q(last_name__icontains=text))
                q3 = patient.filter(Q(NationalCode__icontains=text))
                q4 = patient.filter(Q(mobile__icontains=text))
                item = (q1 | q2 | q3 | q4).order_by('-id')
                print(item)
                return render(request, 'main/search_result.html',{'patient':item,'searchform':Searchbox})
        elif request.POST.get('status') == '2':
            if form.is_valid():
                text =form.cleaned_data['searchtxt']
                reception = Reception.objects.all()
                q1 = reception.filter(Q(EntranceCode__icontains=text))
                q2 = reception.filter(Q(TurnCode__icontains=text))
                q3 = reception.filter(Q(Referrer__icontains=text))
                item = (q1 | q2 | q3 ).order_by('-id')
                return render(request, 'main/search_result.html',{'reception':item})
        elif request.POST.get('status') == '3':
            if form.is_valid():
                text =form.cleaned_data['searchtxt']
                refer = refer_to_surgery.objects.all()
                #q1 = refer.filter(Q(Patient__icontains=text))
                q2 = refer.filter(Q(name__icontains=text))
                q3 = refer.filter(Q(name_Doc__icontains=text))
                #q4 = refer.filter(Q(name__icontains=text))
                #q5 = refer.filter(Q(name_Doc__icontains=text))
                item = ( q2 | q3 ).order_by('-id')
                return render(request, 'main/search_result.html',{'refer':item})
        elif request.POST.get('status') == '4':
            if form.is_valid():
                text =form.cleaned_data['searchtxt']
                turn = Take_Turn.objects.all().filter(Patient__NationalCode__icontains=text)
                turns_list = Take_Turn.objects.all().filter(Patient__NationalCode__icontains=text)
                # patient = Patient.objects.all()
                # q1 = patient.filter(Q(NationalCode__icontains=text))
                # turns_list = []
                # for i in q1:
                #     for j in turn:
                #         if j.Patient == i:
                #             turns_list.append(j)


                #item = ( q2 | q3 ).order_by('-id')
                return render(request, 'main/search_result.html',{'turns':turns_list})
    else:
        return HttpResponse('Invalid Method')
def pationt_list(request):
    patient = Patient.objects.order_by('-id')

    p = Paginator(patient, 50)  # creating a paginator object
    # getting the desired page number from url
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)  # returns the desired page object
    except PageNotAnInteger:
        # if page_number is not an integer then assign the first page
        page_obj = p.page(1)
    except EmptyPage:
        # if page is empty then return last page
        page_obj = p.page(p.num_pages)
    return render(request, 'main/patient_list.html',{'patient':page_obj})

#from collections import OrderedDict
def download(request):
    patient = Patient.objects.order_by('-id')
    patients_list = [[ 'نام',
     'نام خانوادگی',
      'كد ملی',
      'موبایل',
       'سن']]
    #data = OrderedDict()
    for i in patient:
        p_list =[i.p_name,i.last_name,i.NationalCode,i.mobile,i.age]
        patients_list.append(p_list)
    #data.update({"Sheet 1": patients_list})
    #sheet =save_data("your_file.xlsx", data)
    sheet = excel.pe.Sheet(patients_list)
    return excel.make_response(sheet, 'xlsx')
def surgery_list(request):
    surgery = refer_to_surgery.objects.order_by('-id')
    query_set = surgery
    if request.method == 'POST':
        getform = Filter_form(request.POST)
        if getform.is_valid():
            date1 =getform.cleaned_data['from_date']
            date2 =getform.cleaned_data['to_date']
            q1 = query_set.filter(Q(date_time__gte=date1))
            q2 = query_set.filter(Q(date_time__lte=date2))
            surgery = (q1 & q2).order_by('-id')
            form =Filter_form()
            return render(request, 'main/surgery_list.html',{'surgery':surgery,'form':form})
    form =Filter_form()
    return render(request, 'main/surgery_list.html',{'surgery':surgery,'form':form})

def download2(request):
    surgery = refer_to_surgery.objects.order_by('-id')
    patients_list = [['بیمار',
    'عنوان عمل',
    'نام پزشك',
    'وضعیت شرح حال',
    'وضعیت برائت نام',
    'تاریخ جراحی'
    ]]
    #data = OrderedDict()
    for i in surgery:
        if i.patient_history:
            a = "موجود است"
        else:
            a = "موجود نیست"
        if i.Medical_innocence:
            b = "موجود است"
        else:
            b = "موجود نیست"
        x= JalaliDate(DATE.date(i.date_time.year, i.date_time.month, i.date_time.day))
        p_list =[str(i.Patient),i.name,i.name_Doc,a,b,str(x)]
        patients_list.append(p_list)
    #data.update({"Sheet 1": patients_list})
    #sheet =save_data("your_file.xlsx", data)
    sheet = excel.pe.Sheet(patients_list)
    return excel.make_response(sheet, 'xlsx')
def Turn_list(request):
    turns = Take_Turn.objects.order_by('-id')
    query_set = turns
    if request.method == 'POST':
        getform = Filter_form(request.POST)
        if getform.is_valid():
            date1 =getform.cleaned_data['from_date']
            date2 =getform.cleaned_data['to_date']
            q1 = query_set.filter(Q(date_time__gte=date1))
            q2 = query_set.filter(Q(date_time__lte=date2))
            turns = (q1 & q2).order_by('-id')
            form =Filter_form()
            return render(request, 'main/turn_list.html',{'turns':turns,'form':form})
    form =Filter_form()
    return render(request, 'main/turn_list.html',{'turns':turns,'form':form})
def download3(request):
    turns = Take_Turn.objects.order_by('-id')

mainpage/templates/partials/footer.html
                <div class="app-wrapper-footer">
                        <div class="app-footer">
                            <div class="app-footer__inner">
                                <div class="app-footer-right">
                                    <p dir="rtl">
                                      تمامی حقوق مادی و معنوی این سامانه متعلق به دكتر گیو شریفی می باشد.
                                    </p>
                                </div>

                            </div>
                        </div>
                    </div>

mainpage/templates/partials/footer_o.html
                <div class="app-wrapper-footer">
                        <div class="app-footer">
                            <div class="app-footer__inner">
                                <div class="app-footer-right">
                                    <p dir="rtl">
                                      تمامي حقوق مادي و معنوي اين سامانه متعلق به دكتر گيو شريفي مي باشد.
                                    </p>
                                </div>

                            </div>
                        </div>
                    </div>

mainpage/templates/partials/header.html
{% load static %}
{% load main_tags %}
        <div class="app-header header-shadow">
            <div class="app-header__logo">
                <div class="logo-src"></div>
                <div class="header__pane ml-auto">
                    <div>
                        <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="app-header__mobile-menu">
                <div>
                    <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
                    </button>
                </div>
            </div>
            <div class="app-header__menu">
                <span>
                    <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                        <span class="btn-icon-wrapper">
                            <i class="fa fa-ellipsis-v fa-w-6"></i>
                        </span>
                    </button>
                </span>
            </div>    <div class="app-header__content">
                <div class="app-header-left">
                    {% show_search %}
                    <ul class="header-menu nav">
                        <li class="nav-item">
                            <a href="{% url 'main:home' %}" class="nav-link">
                                <i class="nav-link-icon fa fa-home"> </i>
                                خانه
                            </a>
                        </li>
                        <li class="btn-group nav-item">
                            <a href="{% url 'turn:take_turn' %}" class="nav-link">
                                <i class="nav-link-icon fa fa-edit"></i>
                                ثبت نوبت
                            </a>
                        </li>
                        <li class="dropdown nav-item">
                            <a href="{% url 'main:Calender' %}" class="nav-link">
                                <i class="nav-link-icon fa fa-calendar"></i>
                                ثبت تعطیلات
                            </a>
                        </li>
                    </ul>        </div>
                <div class="app-header-right">
                    <div class="header-btn-lg pr-0">
                        <div class="widget-content p-0">
                            <div class="widget-content-wrapper">
                                <div class="widget-content-left">
                                    <div class="btn-group">
                                        <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="p-0 btn">
                                            <img width="42" class="rounded-circle" src="{% static 'images/LOGO.png' %}" alt="">
                                            <i class="fa fa-angle-down ml-2 opacity-8"></i>
                                        </a>
                                        <div tabindex="-1" role="menu" aria-hidden="true" class="dropdown-menu dropdown-menu-right">
                                            <button type="button" tabindex="0" class="dropdown-item">
                                                            user: {{user}}
                              </button>
                              <a  href="{% url 'account:logoutuser' %}"><button type="button" tabindex="0" class="dropdown-item">
                                                          خروج
                              </button></a>

                                        </div>
                                    </div>
                                </div>
                                <div class="widget-content-left  ml-3 header-user-info">
                                    <div class="widget-heading">
                                          سامانه اطلاعات بیماران دکتر شریفی
                                    </div>
                                    <div class="widget-subheading">
                                   
                                    </div>
                                </div>
                                <div class="widget-content-right header-user-info ml-3">

                                </div>
                            </div>
                        </div>
                    </div>        </div>
            </div>
        </div>

mainpage/templates/partials/header_o.html
{% load static %}
{% load main_tags %}
        <div class="app-header header-shadow">
            <div class="app-header__logo">
                <div class="logo-src"></div>
                <div class="header__pane ml-auto">
                    <div>
                        <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="app-header__mobile-menu">
                <div>
                    <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
                    </button>
                </div>
            </div>
            <div class="app-header__menu">
                <span>
                    <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                        <span class="btn-icon-wrapper">
                            <i class="fa fa-ellipsis-v fa-w-6"></i>
                        </span>
                    </button>
                </span>
            </div>    <div class="app-header__content">
                <div class="app-header-left">
                    {% show_search %}
                    <ul class="header-menu nav">
                        <li class="nav-item">
                            <a href="{% url 'main:home' %}" class="nav-link">
                                <i class="nav-link-icon fa fa-home"> </i>
                                خانه
                            </a>
                        </li>
                        <li class="btn-group nav-item">
                            <a href="{% url 'turn:take_turn' %}" class="nav-link">
                                <i class="nav-link-icon fa fa-edit"></i>
                                ثبت نوبت
                            </a>
                        </li>
                        <li class="dropdown nav-item">
                            <a href="{% url 'main:Calender' %}" class="nav-link">
                                <i class="nav-link-icon fa fa-calendar"></i>
                                ثبت تعطيلات
                            </a>
                        </li>
                    </ul>        </div>
                <div class="app-header-right">
                    <div class="header-btn-lg pr-0">
                        <div class="widget-content p-0">
                            <div class="widget-content-wrapper">
                                <div class="widget-content-left">
                                    <div class="btn-group">
                                        <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="p-0 btn">
                                            <img width="42" class="rounded-circle" src="{% static 'images/LOGO.png' %}" alt="">
                                            <i class="fa fa-angle-down ml-2 opacity-8"></i>
                                        </a>
                                        <div tabindex="-1" role="menu" aria-hidden="true" class="dropdown-menu dropdown-menu-right">
                                            <button type="button" tabindex="0" class="dropdown-item">
                                                            user: {{user}}
                              </button>

                                        </div>
                                    </div>
                                </div>
                                <div class="widget-content-left  ml-3 header-user-info">
                                    <div class="widget-heading">
                                        دكتر گيو شريفي
                                    </div>
                                    <div class="widget-subheading">
                                        سامانه ثبت اطلاعات بيماران
                                    </div>
                                </div>
                                <div class="widget-content-right header-user-info ml-3">

                                </div>
                            </div>
                        </div>
                    </div>        </div>
            </div>
        </div>

mainpage/templates/partials/sidebar.html
<div class="app-sidebar sidebar-shadow">
    <div class="app-header__logo">
        <div class="logo-src"></div>
        <div class="header__pane ml-auto">
            <div>
                <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                    <span class="hamburger-box">
                        <span class="hamburger-inner"></span>
                    </span>
                </button>
            </div>
        </div>
    </div>
    <div class="app-header__mobile-menu">
        <div>
            <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                </span>
            </button>
        </div>
    </div>
    <div class="app-header__menu">
        <span>
            <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                <span class="btn-icon-wrapper">
                    <i class="fa fa-ellipsis-v fa-w-6"></i>
                </span>
            </button>
        </span>
    </div>
    <div class="scrollbar-sidebar">
        <div class="app-sidebar__inner">
            <ul class="vertical-nav-menu">
              <li class="app-sidebar__heading">بیماران</li>
              <li>
                  <a href="{% url 'main:pationt_list' %}">
                      <i class="metismenu-icon pe-7s-star"></i>
                      لیست بیماران
                  </a>

              </li>
                <li class="app-sidebar__heading">نوبت</li>
                <li>
                  <a href="{% url 'turn:take_turn' %}">
                      <i class="metismenu-icon pe-7s-pen"></i>
                      ثبت نوبت
                  </a>
                    <a href="{% url 'main:Turn_list' %}">
                        <i class="metismenu-icon pe-7s-pin"></i>
                        لیست نوبت ها
                    </a>


                </li>
                <li class="app-sidebar__heading">جراحی</li>
                <li>
                    <a href="{% url 'reception:reToSurgery' %}">
                        <i class="metismenu-icon pe-7s-pen"></i>
                        ثبت جراحی
                    </a>
                    <a href="{% url 'main:surgery_list' %}">
                        <i class="metismenu-icon pe-7s-pin"></i>
                        لیست ارجاع به جراحی
                    </a>

                </li>
                <li class="app-sidebar__heading">پذیرش</li>
                <li>
                    <a href="{% url 'reception:listRec' %}">
                        <i class="metismenu-icon pe-7s-pin"></i>
                        لیست پذیرش
                    </a>
                </li>




            </ul>
        </div>
    </div>
</div>

mainpage/templates/partials/sidebar_o.html
<div class="app-sidebar sidebar-shadow">
    <div class="app-header__logo">
        <div class="logo-src"></div>
        <div class="header__pane ml-auto">
            <div>
                <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                    <span class="hamburger-box">
                        <span class="hamburger-inner"></span>
                    </span>
                </button>
            </div>
        </div>
    </div>
    <div class="app-header__mobile-menu">
        <div>
            <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                </span>
            </button>
        </div>
    </div>
    <div class="app-header__menu">
        <span>
            <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                <span class="btn-icon-wrapper">
                    <i class="fa fa-ellipsis-v fa-w-6"></i>
                </span>
            </button>
        </span>
    </div>
    <div class="scrollbar-sidebar">
        <div class="app-sidebar__inner">
            <ul class="vertical-nav-menu">
              <li class="app-sidebar__heading">بيماران</li>
              <li>
                  <a href="{% url 'main:pationt_list' %}">
                      <i class="metismenu-icon pe-7s-star"></i>
                      ليست بيماران
                  </a>

              </li>
                <li class="app-sidebar__heading">نوبت</li>
                <li>
                  <a href="{% url 'turn:take_turn' %}">
                      <i class="metismenu-icon pe-7s-pen"></i>
                      ثبت نوبت
                  </a>
                    <a href="{% url 'main:Turn_list' %}">
                        <i class="metismenu-icon pe-7s-pin"></i>
                        ليست نوبت ها
                    </a>


                </li>
                <li class="app-sidebar__heading">جراحي</li>
                <li>
                    <a href="{% url 'reception:reToSurgery' %}">
                        <i class="metismenu-icon pe-7s-pen"></i>
                        ثبت جراحي
                    </a>
                    <a href="{% url 'main:surgery_list' %}">
                        <i class="metismenu-icon pe-7s-pin"></i>
                        ليست ارجاع به جراحي
                    </a>
                </li>




            </ul>
        </div>
    </div>
</div>