account/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views

app_name = 'account'

urlpatterns = [

    path('login/', csrf_exempt(views.user_login), name='login'),
    path('profile/', views.profile, name='profile'),
    path('logout',views.logoutuser, name='logoutuser')
]

clinic/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('reception/', include('reception.urls',namespace='reception')),
    path('take_turn/', include('take_turn.urls',namespace='turn')),
    path('accounts/', include('account.urls',namespace='account')),

    path('da/', include('dashboard.urls', namespace='dashboard')),
    path('', include('mainpage.urls', namespace='main')),

]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mainpage/urls.py
from django.urls import  path
from . import views
app_name = 'main'
urlpatterns = [

    path('', views.Home, name= 'home'),
    path('search/',views.searchb_us,name='search'),
    path('report/',views.pationt_list, name='pationt_list'),
    path('surgery_list/',views.surgery_list, name='surgery_list'),
    path('Turn_list/',views.Turn_list, name='Turn_list'),
    path('create',views.creatFile, name='creatFile'),
    path('calender',views.Calender, name='Calender'),
    path('<int:id>/', views.patient_file,name='patient_file'),
    path('p_download', views.download, name="p_download"),
    path('s_download', views.download2, name="s_download"),
    path('t_download', views.download3, name="t_download"),
    path('res_download', views.download4, name="p_download4")


]

reception/urls.py
from django.urls import  path
from . import views
app_name = 'reception'
urlpatterns = [
    path('List', views.list_of_rec, name='listRec'),
    path('reToSurgery/', views.reToSurgery, name= 'reToSurgery'),
    path('<int:id>', views.reception_form, name= 'reception'),
    path('<int:id>/<int:EntranceCode>', views.recption_detail, name= 'receptionDetaile'),
    path('surgery/<int:id>', views.Refer_Surgery, name= 'Refer_Surgery'),
]

take_turn/urls.py
from django.urls import  path
from . import views
app_name = 'turn'
urlpatterns = [
    path('', views.take_turn, name= 'take_turn'),
    path('<int:id>', views.take_turn_s, name= 'take_turn_s'),
    path('del/<int:id>', views.delete_turn, name= 'delete_turn'),
    path('delh/<int:id>', views.delete_turn_h, name= 'delete_turn_h'),

]

mainpage/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime, date
from jalali_date import date2jalali, datetime2jalali
from django.conf import settings
# Create your models here.
class day_of(models.Model):
    Description =models.TextField(max_length=2000, null=True, blank=True, verbose_name="توضیحات")
    date_time = models.DateField(auto_now_add=False,auto_now=False, verbose_name="تاریخ")
    def __str__(self):
        return str(self.date_time)

    class Meta:
        verbose_name = "روز تعطیل"
        verbose_name_plural = "روزهای تعطیل"
    def get_jalali_date(self):
        return date2jalali(self.date_time)

class Patient(models.Model):
    GENDER_CHOICES = ((0, 'زن'), (1, 'مرد'))
    NationalCode =  models.CharField(max_length = 10, unique=True,verbose_name="کد ملی")
    p_name = models.CharField(max_length=100,null=True, blank=True, verbose_name="نام")
    last_name = models.CharField(max_length=100,null=True, blank=True, verbose_name="نام خانوادگی")
    mobile = models.CharField(max_length=13, verbose_name="تلفن همراه")
    land_line_phone = models.CharField(max_length=13,null=True, blank=True, verbose_name="تلفن ثابت")
    age = models.IntegerField(null=True, blank=True, verbose_name="سن بیمار")
    Gender = models.IntegerField(choices=GENDER_CHOICES,null=True, blank=True, verbose_name="جنسیت")
    def __str__(self):
        return '{} {} ({})'.format(self.p_name, self.last_name, self.NationalCode)
    def get_absolute_url(self):
        if self.NationalCode != None:
            return reverse('main:patient_file', args=[self.id])
        else:
            return reverse('main:patient_file', args=[self.pk])

#------------------
class Clinic(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True, verbose_name="نام کلینیک")
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "کلینیک"
        verbose_name_plural = "کلینیک ها"
class Take_Turn(models.Model):
    part_choice = ((
        0, 'post-مغز'
        ),(
        1, 'post-کمر'
        ),(
        2,'post-هیپوفیز'
        ),(
        3, 'new-مغز'
        ),(
        4, 'new-کمر'
        ),(
        5, 'new-هیپوفیز'
        ),(
        6, 'بخیه-مغز'
        ),(
        7, 'بخیه-کمر'
        ),(
        8, 'post_گردن'
        ),(
        9, 'new_گردن'
        ))
    TURN_TYPE = ((0, 'حضوری'), (1, 'تلفنی'), (2, 'فکس'))
    Patient = models.ForeignKey('Patient', related_name='Patient1', on_delete=models.CASCADE, verbose_name="پرونده")
    TurnCode = models.CharField(max_length=10,verbose_name="کد وقت")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True,related_name='turn',on_delete=models.CASCADE)
    part = models.IntegerField(choices=part_choice, verbose_name='بخش')
 #   Day = models.IntegerField(choices=WEEK_DAY, verbose_name="روز")
    #clinic = models.ForeignKey('Clinic', related_name='clinic', on_delete=models.CASCADE, verbose_name="کلینیک")
    date = models.DateTimeField(auto_now=True,verbose_name="تاریخ ثبت نوبت")
    date_time = models.DateTimeField(auto_now_add=False,auto_now=False,blank=True, verbose_name="(2021-01-01)تاریخ نوبت")
    TypeTurn = models.IntegerField(choices=TURN_TYPE, null=True, blank=True, verbose_name="نوع در خواست وقت")
    Description =models.TextField(max_length=2000, null=True, blank=True, verbose_name="توضیحات")
    def __str__(self):
        return str(self.Patient)

    class Meta:
        verbose_name = "نوبت"
        verbose_name_plural = "نوبت ها"
    def get_jalali_date(self):
        return datetime2jalali(self.date_time)


#پذیرش
class Services(models.Model):
    Service = models.CharField(max_length=100, verbose_name="نام خدمت")
    Price = models.DecimalField(max_digits=10, decimal_places=2,default= 0)

    def __str__(self):
        return self.Service
    class Meta:
        verbose_name = "خدمت"
        verbose_name_plural = "خدمت های قابل ارائه"
class Diagnosis(models.Model):
    D_name = models.CharField(max_length=200, verbose_name="نام خدمت")
    def __str__(self):
        return self.D_name
    class Meta:
        verbose_name = "تشخیص"
        verbose_name_plural = "تشخیص"

# Create your models here.
class Reception (models.Model):
    LEVEL = ((0, 'جدید'), (1, 'بعد از عمل'), (2,'رویت MRA'))

    Patient = models.ForeignKey('Patient', related_name='Patient2', on_delete=models.CASCADE, verbose_name="پرونده")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True,related_name='reception',on_delete=models.CASCADE)
    TypeTurn = models.IntegerField(choices=LEVEL, default=0, verbose_name="مرحله")
    #Receptionist = models.ForeignKey('Receptionist', related_name='Receptionist', on_delete=models.SET_NULL,verbose_name="مسئول پذیرش")

    EntranceCode = models.IntegerField(verbose_name="کد پذیرش")
    TurnCode = models.CharField(max_length=10,verbose_name="کد وقت")
    EntranceDate = models.DateTimeField(auto_now=True,verbose_name="تاریخ پذیرش")
    date = models.DateTimeField(verbose_name="تاریخ نوبت")
    Referrer = models.CharField(max_length=100,null=True, blank=True, verbose_name="معرف")
    Description =models.TextField(max_length=2000, null=True, blank=True, verbose_name="توضیحات")
    Payable = models.IntegerField(verbose_name="قابل پرداخت",default=0)
    def __str__(self):
                return str(self.Patient)

    class Meta:
        verbose_name = "بیمار"
        verbose_name_plural = "بیماران پذیرش شده"
    def get_absolute_url(self):
        return reverse('reception:receptionDetaile',args=[self.id, self.EntranceCode])
    def get_jalali_date(self):
        return datetime2jalali(self.EntranceDate)
class PatientItem(models.Model):
    Reception = models.ForeignKey(Reception,related_name='items',on_delete=models.CASCADE, null=True)
    Services = models.ForeignKey(Services,related_name='order_items',on_delete=models.CASCADE, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    def __str__(self):
        return str(self.Services)
    def get_cost(self):
        return self.price * self.quantity

class PatientDiagnosis(models.Model):
    reception = models.ForeignKey(Reception,related_name='diagnisisReception',on_delete=models.CASCADE, null=True)
    diagnisis = models.ForeignKey(Diagnosis,related_name='diagnisis',on_delete=models.CASCADE, null=True)
    def __str__(self):
        return str(self.diagnisis)


#**********

mainpage/forms.py
from django import forms
from .models import Patient,day_of
from jalali_date.fields import JalaliDateField
from jalali_date.widgets import AdminJalaliDateWidget, AdminSplitJalaliDateTime
class Searchbox (forms.Form):
    searchtxt=forms.CharField (max_length=100, widget=forms.TextInput(attrs={'class':'search-input', 'placeholder':"جستجوی پرونده" }))
class patientEditForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ('NationalCode', 'p_name', 'last_name', 'mobile','land_line_phone','age','Gender')
    def __init__(self, *args, **kwargs):
        super(patientEditForm,self).__init__(*args, **kwargs)
        self.fields['NationalCode'].widget.attrs['class'] = 'form-control'
        self.fields['p_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['mobile'].widget.attrs['class'] = 'form-control'
        self.fields['land_line_phone'].widget.attrs['class'] = 'form-control'
        self.fields['age'].widget.attrs['class'] = 'form-control'
        self.fields['Gender'].widget.attrs['class'] = 'form-control'
CHOICE_LIST = [
    ('', 'جنسیت'), # replace the value '----' with whatever you want, it won't matter
    (0, 'زن'),
    (1, 'مرد')
]
class patientTotalForm(forms.ModelForm):
    Gender=forms.ChoiceField(choices=CHOICE_LIST, required=False)
    class Meta:
        model = Patient
        fields = ( 'NationalCode','p_name', 'last_name', 'mobile','land_line_phone','age')
    def __init__(self, *args, **kwargs):
        super(patientTotalForm,self).__init__(*args, **kwargs)
        self.fields['Gender'].empty_label = "(Select here)"
        self.fields['Gender'].widget.attrs['class'] = 'siavash'

class day_ofEditForm(forms.ModelForm):
    class Meta:
        model = day_of
        fields = ('date_time','Description')
    def __init__(self, *args, **kwargs):
        super(day_ofEditForm,self).__init__(*args, **kwargs)
        self.fields['date_time'] = JalaliDateField(label=('تاریخ'), # date format is  "yyyy-mm-dd"
            widget=AdminJalaliDateWidget
           # optional, to use default datepicker
        )
        self.fields['date_time'].widget.attrs['class'] = 'form-control'
        self.fields['Description'].widget.attrs['class'] = 'form-control'
class Filter_form(forms.Form):
    from_date = forms.DateTimeField()
    to_date = forms.DateTimeField()
    def __init__(self, *args, **kwargs):
        super(Filter_form,self).__init__(*args, **kwargs)
        self.fields['from_date'] = JalaliDateField(label=('از تاریخ'), # date format is  "yyyy-mm-dd"
            widget=AdminJalaliDateWidget
           # optional, to use default datepicker
        )
        self.fields['to_date'] = JalaliDateField(label=("تا تاریخ"),  # date format is  "yyyy-mm-dd"
            widget=AdminJalaliDateWidget
           # optional, to use default datepicker
        )

mainpage/templates/main/base1.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <link href="{% static 'css/main.css' %}?v=69" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/mdtimepicker.css' %}">
    {% block custom_css %}  {% endblock %}
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
<div class="navbar" style="border-bottom:1px solid lightgray;">
  <ul>

    <li><a   href="{% url 'main:home' %}">خانه</a></li>
    <li><a href="{% url 'turn:take_turn' %}">فرم وقت دهی  بیماران</a></li>   
    <li><a  href="{% url 'main:Turn_list' %}">لیست نوبت</a></li>
    <li><a  href="{% url 'main:pationt_list' %}">لیست بیماران</a></li>    
    <li><a  href="{% url 'main:surgery_list' %}">لیست ارجاع جراحی</a></li>

    <li><a  href="{% url 'main:Calender' %}">ثبت تعطیلات</a></li>
    <li><a  href="{% url 'reception:reToSurgery' %}">ارجاع به جراحی</a></li>

    <li><a  href="{% url 'account:logoutuser' %}">خروج</a></li>
  </ul>

</div>
    {% block content %}

    {% endblock %}

<script src="{% static 'js/mdtimepicker.js' %}"></script>
<script src="{% static 'js/Mh1PersianDatePicker.js' %}"></script>
<script>
    $(document).ready(function () {
        $('#id_date_1').mdtimepicker({
            timeFormat: 'hh:mm:ss.000', // format of the time value (data-time attribute)
            format: 'hh:mm tt',    // format of the input value
            readOnly: false,       // determines if input is readonly
            hourPadding: false,
            theme: 'blue',
            okLabel: 'تائید',
            cancelLabel: 'انصراف',
        });
        $('#id_date_time_1').mdtimepicker({
            timeFormat: 'hh:mm:ss.000', // format of the time value (data-time attribute)
            format: 'hh:mm tt',    // format of the input value
            readOnly: false,       // determines if input is readonly
            hourPadding: false,
            theme: 'blue',
            okLabel: 'تائید',
            cancelLabel: 'انصراف',
        });
    });
</script>

  </body>
</html>

mainpage/templates/main/base1_o.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <link href="{% static 'css/main.css' %}?v=69" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/mdtimepicker.css' %}">
    {% block custom_css %}  {% endblock %}
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
<div class="navbar" style="border-bottom:1px solid lightgray;">
  <ul>

    <li><a   href="{% url 'main:home' %}">خانه</a></li>
    <li><a href="{% url 'turn:take_turn' %}">فرم وقت دهی  بیماران</a></li>   
    <li><a  href="{% url 'main:Turn_list' %}">لیست نوبت</a></li>
    <li><a  href="{% url 'main:pationt_list' %}">لیست بیماران</a></li>    
    <li><a  href="{% url 'main:surgery_list' %}">لیست ارجاع جراحی</a></li>

    <li><a  href="{% url 'main:Calender' %}">ثبت تعطیلات</a></li>
    <li><a  href="{% url 'reception:reToSurgery' %}">ارجاع به جراحی</a></li>

    <li><a  href="{% url 'account:logoutuser' %}">خروج</a></li>
  </ul>

</div>
    {% block content %}

    {% endblock %}

<script src="{% static 'js/mdtimepicker.js' %}"></script>
<script src="{% static 'js/Mh1PersianDatePicker.js' %}"></script>
<script>
    $(document).ready(function () {
        $('#id_date_1').mdtimepicker({
            timeFormat: 'hh:mm:ss.000', // format of the time value (data-time attribute)
            format: 'hh:mm tt',    // format of the input value
            readOnly: false,       // determines if input is readonly
            hourPadding: false,
            theme: 'blue',
            okLabel: 'تائید',
            cancelLabel: 'انصراف',
        });
        $('#id_date_time_1').mdtimepicker({
            timeFormat: 'hh:mm:ss.000', // format of the time value (data-time attribute)
            format: 'hh:mm tt',    // format of the input value
            readOnly: false,       // determines if input is readonly
            hourPadding: false,
            theme: 'blue',
            okLabel: 'تائید',
            cancelLabel: 'انصراف',
        });
    });
</script>

  </body>
</html>

mainpage/templates/main/create.html
{% extends "main/base.html" %}
{% load static %}
{% block custom_css %}<link href="{% static 'css/detail.css' %}?v=11" rel="stylesheet">{% endblock %}
{% block title %}p_login{% endblock %}
{% block content %}
<div class="creat_f">



    <form class="" action="{% url 'main:creatFile' %}" method="post">
      {% csrf_token %}
      <table class="creatFile_f">
        <caption><h2>ایجاد پرونده جدید</h2></caption>
        <tbody>
          <tr>
            <td>{{form.NationalCode}}</td>
            <td>{{form.p_name}}</td>
          </tr>
        </tbody>
        <tbody>
          <tr>
            <td>{{form.last_name}}</td>
            <td>{{form.mobile}}</td>
          </tr>
        </tbody>
        <tbody>
          <tr>
            <td>{{form.land_line_phone}}</td>
            <td>{{form.age}}</td>
          </tr>
        </tbody>
        <tbody>
          <tr>
            <td>{{form.Gender}}</td>
          </tr>
        </tbody>
      </table>

      <button class="ebtn" type="submit" name="button">ایجاد پرونده</button>
    </form>



</div>

<script type="text/javascript">
      document.getElementById('id_NationalCode').placeholder ='کد ملی';
      document.getElementById('id_p_name').placeholder ='نام';
      document.getElementById('id_last_name').placeholder ='نام خانوادگی';
      document.getElementById('id_mobile').placeholder ='شماره موبایل';
      document.getElementById('id_land_line_phone').placeholder ='شماره ثابت';
      document.getElementById('id_age').placeholder ='سن';
</script>
<script type="text/javascript">
  var content = document.getElementById('id_Gender');
  var firstChild = content.firstChild;
  firstChild.innerHTML = "جنسیت";
</script>
{% endblock %}

mainpage/templates/main/day_of1_o.html
{% extends "main/base1.html" %}
{% load static %}
{% load jalali_tags %}
{% block title %}p_login{% endblock %}
{% block custom_css %}
<link href="{% static 'css/day_of.css' %}?v=6" rel="stylesheet">
<link href="{% static 'css/Mh1PersianDatePicker.css' %}" rel="stylesheet" />
{% endblock %}
{% block content %}
  <div class="day_of_box">

    <form class="" action="{% url 'main:Calender' %}" method="post">
      {% csrf_token %}
      <table class="Form-Table table-hover">
        <caption class="text-center"><h2>ثبت روز تعطيل</h2></caption>
        <thead>
          <tr>
            <th data-priority="1">{{form.date_time.label}}</th>
            <th data-priority="2">{{form.Description.label}}</th>


          </tr>
        </thead>
        <tbody>

          <tr>
            <td>{{form.date_time}}</td>
            <td>{{form.Description}}</td>
          </tr>
        </tbody>
        <thead>
          <th><button class="ebtn" style="width: 100%; height: 100%;margin:0;"  type="submit" name="button">ثبت</button></th>
        </thead>
        <tbody>
          <td> </td>
        </tbody>
      </table>
    </form>


    <div class="day_of_middel">
      سيستم مديريت كلينيك
    </div>

    <table class="table-bordered table-hover">
      <caption class="text-center"><h2>نوبت های صادر شده </h2></caption>
      <thead>
        <tr>
          <th data-priority="1">تاريخ تعطيل</th>
          <th data-priority="2">مناسبت</th>
        </tr>
      </thead>
      <tbody>
        {% for i in lsit_day %}
        <tr>
          <td>{{i.get_jalali_date}}</td>
          <td>{{i.Description}}</td>
        </tr>
        {% empty %}
        <td class="turn_li">روز تعطيل ثبت نشده است</td>
        {% endfor %}
      </tbody>
    </table>


  </div>
  <link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
  <script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
  <script src="{% static 'js/Mh1PersianDatePicker.js' %}"></script>
  <script type="text/javascript">
      window.holidays = [];
  </script>
  {% for i in lsit_day %}
  <script type="text/javascript">
    window.holidays.push('{{i.get_jalali_date}}')
  </script>
  {% endfor %}

  <script>
      //script1
    //  var inputs = document.querySelectorAll('#id_date_time');

      for (i = 0; i < inputs.length; i++) {
          (function (i) {
            inputs[i].addEventListener('click', function () {
                  Mh1PersianDatePicker.Show(this, '{{today}}', window.holidays);
              });
          })(i);
      }
      //script1
  </script>

  {{ form.media }}
{% endblock %}

mainpage/templates/main/day_of_o.html
{% extends "main/layout.html" %}
{% load static %}
{% block styles %}
<link href="{% static 'css/Mh1PersianDatePicker.css' %}" rel="stylesheet" />
 <link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
{% endblock %}
{% block content %}
<style media="screen">
  .myform textarea{
    height:40px;
  }
</style>
                    <div class="app-main__inner">
                      <div class="main-card mb-3 card" style="justify-content: right;">
                          <div class="card-body" style="justify-content: right;"><h5 class="card-title" style="text-align: center;">ایجاد تعطیلات</h5>
                              <div>
                                  <form style="justify-content: space-around; direction: rtl; " class="form-inline" action="{% url 'main:Calender' %}" method="post">

                                      <div class="mb-2 mr-sm-2 mb-sm-0 position-relative form-group myform" >
                                        {% csrf_token %}
                                          تاریخ
                                        {{form.date_time}}

                                      </div>
                                       <div class="mb-2 mr-sm-2 mb-sm-0 position-relative form-group myform" >
                                            مناسبت
                                          {{form.Description}}
                                      </div>
                                      <button class="btn btn-primary" type="submit">ثبت</button>
                                  </form>
                              </div>
                          </div>
                      </div>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="main-card mb-3 card">
                                    <div class="card-header">
                                        <div class="btn-actions-pane-right">
                                            <div role="group" class="btn-group-sm btn-group">
                                                <button class="active btn btn-focus">لیست تعطیلات</button>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="table-responsive">
                                        <table class="align-middle mb-0 table table-borderless table-striped table-hover">
                                            <thead>
                                            <tr>
                                                <th class="text-center">تاریخ تعطیلات</th>

                                                <th class="text-center">مناسبت</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                              {% for i in lsit_day %}
                                            <tr>
                                                <td class="text-center text-muted">
                                                  {{i.get_jalali_date}}
                                                </td>
                                                <td>
                                                  {{i.Description}}
                                                </td>
                                            </tr>
                                          {% empty %}

                                          <td class="text-center">
                                              تعطیلاتی تعریف نشده است
                                          </td>
                                          <td>-</td>

                                          {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
<script type="text/javascript">id_status
  document.getElementById('id_searchtxt').placeholder ='جستجو';
  document.getElementById('id_status').value = '1';
</script>
  <script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
  <script src="{% static 'js/Mh1PersianDatePicker.js' %}"></script>
  <script type="text/javascript">
      window.holidays = [];
  </script>
  {% for i in lsit_day %}
  <script type="text/javascript">
    window.holidays.push('{{i.get_jalali_date}}')
  </script>
  {% endfor %}

  <script>
      //script1
    //  var inputs = document.querySelectorAll('#id_date_time');

      for (i = 0; i < inputs.length; i++) {
          (function (i) {
            inputs[i].addEventListener('click', function () {
                  Mh1PersianDatePicker.Show(this, '{{today}}', window.holidays);
              });
          })(i);
      }
      //script1
  </script>

  {{ form.media }}
{% endblock %}

mainpage/templates/main/home.html
{% extends "main/layout.html" %}
{% load static %}

{% block content %}

                    <div class="app-main__inner">

                        <div class="row">
                            <div class="col-md-12">
                                <div class="main-card mb-3 card">
                                    <div class="card-header">
                                        <div class="btn-actions-pane-right">
                                            <div role="group" class="btn-group-sm btn-group">
                                                <button class="active btn btn-focus">نوبت های امروز</button>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="table-responsive">
                                        <table class="align-middle mb-0 table table-borderless table-striped table-hover">
                                            <thead>
                                            <tr>
                                                <th class="text-center">بیمار</th>
                                                <th class="text-center">شماره</th>
                                                <th class="text-center">خدمت</th>
                                                <th class="text-center">همكار</th>
                                                <th>تاریخ</th>
                                                <th class="text-center">حذف نوبت</th>





                                            </tr>
                                            </thead>
                                            <tbody>
                                              {% for i in turn %}
                                            <tr>
                                                                                                <td class="text-center">
                                                  <a href="{{i.Patient.get_absolute_url}}"><button type="button" id="PopoverCustomT-1" class="btn btn-primary btn-sm">{{i.Patient}}</button></a>

                                                </td>


                                                <td class="text-center">
                                                  {{i.TurnCode}}
                                                </td>
                                                                                                <td class="text-center">
                                                  {% if i.part == 0 %}
                                                   'Post-مغز'
                                                  {% elif i.part == 1 %}
                                                      'post-کمر'
                                                    {% elif i.part == 2 %}
                                                     'post-هیپوفیز'
                                                    {% elif i.part == 3 %}
                                                    'new-مغز'
                                                    {% elif i.part == 4 %}
                                                    'new-کمر'
                                                    {% elif i.part == 5 %}
                                                      'new-هیپوفیز'
                                                    {% elif i.part == 6 %}
                                                     'بخیه-مغز'
                                                    {% elif i.part == 7 %}
                                                      'بخیه-کمر'
                                                    {% endif %}
                                                </td>
                                                <td class="text-center">{{i.user}}</td>

                                                                                                <td>
                                                  {{i.get_jalali_date}}
                                                </td>
                                                <td class="text-center text-muted">
                                                  <form  action="{% url 'turn:delete_turn_h' i.id %}" method="post">
                                                    {% csrf_token %}
                                                    <button class="mr-2 btn-icon btn-icon-only btn btn-outline-danger" type="submit"><i class="pe-7s-trash btn-icon-wrapper"> </i></button>
                                                  </form>
                                                </td>





                                            </tr>
                                          {% empty %}

                                          <td class="text-center">
                                              نوبتی برای امروز ثبت نشده است.
                                          </td>
                                          <td>-</td>
                                          <td>-</td>
                                          <td>-</td>
                                          <td>-</td>
                                          <td>-</td>
                                          {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="d-block text-center card-footer">
                                      <a  href="{% url 'main:Turn_list' %}"><button class="btn-wide btn btn-success">لیست  نوبت</button></a>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

    <script type="text/javascript">
      document.getElementById('id_searchtxt').placeholder ='جستجو پرونده: شماره ملی، تلفن، نام';
      document.getElementById('id_status').value = '1';
    </script>
{% endblock %}