clinic/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('reception/', include('reception.urls',namespace='reception')),
    path('take_turn/', include('take_turn.urls',namespace='turn')),
    path('accounts/', include('account.urls',namespace='account')),

    path('da/', include('dashboard.urls', namespace='dashboard')),
    path('', include('mainpage.urls', namespace='main')),

]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mainpage/urls.py
from django.urls import  path
from . import views
app_name = 'main'
urlpatterns = [

    path('', views.Home, name= 'home'),
    path('search/',views.searchb_us,name='search'),
    path('report/',views.pationt_list, name='pationt_list'),
    path('surgery_list/',views.surgery_list, name='surgery_list'),
    path('Turn_list/',views.Turn_list, name='Turn_list'),
    path('create',views.creatFile, name='creatFile'),
    path('calender',views.Calender, name='Calender'),
    path('<int:id>/', views.patient_file,name='patient_file'),
    path('p_download', views.download, name="p_download"),
    path('s_download', views.download2, name="s_download"),
    path('t_download', views.download3, name="t_download"),
    path('res_download', views.download4, name="p_download4")


]

take_turn/urls.py
from django.urls import  path
from . import views
app_name = 'turn'
urlpatterns = [
    path('', views.take_turn, name= 'take_turn'),
    path('<int:id>', views.take_turn_s, name= 'take_turn_s'),
    path('del/<int:id>', views.delete_turn, name= 'delete_turn'),
    path('delh/<int:id>', views.delete_turn_h, name= 'delete_turn_h'),

]

take_turn/models.py
from django.db import models

# Create your models here.

take_turn/forms.py
from django import forms
from jalali_date.fields import JalaliDateField,SplitJalaliDateTimeField
from jalali_date.widgets import AdminJalaliDateWidget, AdminSplitJalaliDateTime
from mainpage.models import Take_Turn
from django.contrib.admin.widgets import AdminDateWidget
from django.forms.fields import DateField
'''
CHOICE_LIST1 = [
    ('', 'روز هاي هفته'), # replace the value '----' with whatever you want, it won't matter
    (0, 'شنبه'),
    (1,' یک شنبه '),
    (2,' دوشنبه '),
    (3,' سه شنبه '),
    (4,' چهار شنبه '),
    (5,' پنجشنبه '),
    (6,' جمعه ')
]'''
CHOICE_LIST2 = [
    ('', 'جنسيت'), # replace the value '----' with whatever you want, it won't matter
    (0, 'زن'),
    (1, 'مرد')
]
CHOICE_LIST3 = [
    (1, 'نوع درخواست'), # replace the value '----' with whatever you want, it won't matter
(0, 'حضوری'),
 (1, 'تلفنی'),
  (2, 'فکس')
]


class TakeTurnEditForm(forms.ModelForm):

    Patient = forms.CharField(label='شماره ملی')
    mobile = forms.CharField(label='شماره همراه')
    First_name = forms.CharField(label='نام', required=False)
    Last_name = forms.CharField(label='نام خانوادگی', required=False)
 #   Day= forms.ChoiceField(choices=CHOICE_LIST1, required=False)
    TypeTurn= forms.ChoiceField(choices=CHOICE_LIST3, required=False)
    class Meta:
        model = Take_Turn
        fields = (
         'part',
         'date_time','Description')
    def __init__(self, *args, **kwargs):
        super(TakeTurnEditForm,self).__init__(*args, **kwargs)
        self.fields['Patient'].widget.attrs['class'] = 'form-control'
        self.fields['mobile'].widget.attrs['class'] = 'form-control'
        self.fields['First_name'].widget.attrs['class'] = 'form-control'
        self.fields['Last_name'].widget.attrs['class'] = 'form-control'
        self.fields['TypeTurn'].widget.attrs['class'] = 'form-control'
        self.fields['part'].widget.attrs['class'] = 'form-control'
        self.fields['date_time'].widget.attrs['class'] = 'form-control'
        self.fields['Description'].widget.attrs['class'] = 'form-control'
        self.fields['date_time'] = SplitJalaliDateTimeField(label=('date time'),)
class TakeTurnEditForm_S(forms.ModelForm):
 #   Day= forms.ChoiceField(choices=CHOICE_LIST1, required=False)
    TypeTurn= forms.ChoiceField(choices=CHOICE_LIST3, required=False)
    class Meta:
        model = Take_Turn
        fields = (
         'part','date_time',
          'Description')
    def __init__(self, *args, **kwargs):
        super(TakeTurnEditForm_S,self).__init__(*args, **kwargs)
        self.fields['TypeTurn'].widget.attrs['class'] = 'form-control'
        self.fields['part'].widget.attrs['class'] = 'form-control'
        self.fields['date_time'].widget.attrs['class'] = 'form-control'
        self.fields['Description'].widget.attrs['class'] = 'form-control'


        self.fields['date_time'] = SplitJalaliDateTimeField(label=('date time'),)
        self.fields['date_time'].empty_label='--كلينيك--'

take_turn/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import TakeTurnEditForm,TakeTurnEditForm_S
from mainpage.models import Take_Turn,Patient,day_of
from django.contrib.auth.models import User
import pytz
import time
from datetime import datetime, timedelta,date
from jalali_date import date2jalali
from account.check_user import chech_profile
# Create your views here.
def take_turn(request):
    user = request.user
    x = chech_profile(user, 10)
    if x == True:
        all_t = Take_Turn.objects.order_by('-date_time')
        all_turns = []
        tz = pytz.timezone('Asia/Tehran')
        for i in all_t:
            if tz.localize(datetime.now())> i.date_time:
                all_turns.append(i)
            else:
                all_turns.append(i)
        if request.method == 'POST':
            turn_form = TakeTurnEditForm(request.POST)
            if turn_form.is_valid():
                AllPatient =Patient.objects.all()
                cd =turn_form.cleaned_data
                part1 = cd['part']
                d = cd['date_time']
                count = 1
                for i in all_turns:
                    d1 = i.date_time
                    if d1.date() == d.date() and part1 == i.part:
                        count += 1
                partlist = ['PM-','PK-','PH-','NM-','NK-','PH-','BM-','BK-','PG-','NG-']
                turncode = partlist[part1] + str(count)
                patient1 = cd['Patient']
                for patient in AllPatient:
                    if patient.NationalCode == patient1:
                        P =Patient.objects.get(NationalCode=patient1)
                        Take_Turn.objects.create(Patient=P,TurnCode = turncode,user=user,part=cd['part'],date_time=cd['date_time'],TypeTurn=cd['TypeTurn'],Description=cd['Description'])
                        
                        return redirect('turn:take_turn')
                Npationt=Patient.objects.create(NationalCode=cd['Patient'],mobile=cd['mobile'],p_name=cd['First_name'],last_name=cd['Last_name'])
                Take_Turn.objects.create(Patient=Npationt ,TurnCode=turncode,user=user,part=cd['part'],date_time=cd['date_time'],TypeTurn=cd['TypeTurn'],Description=cd['Description'])
                form = TakeTurnEditForm()
                return redirect('main:home')
            else:
                pass

        all_turns = Take_Turn.objects.order_by('-date_time')
        form = TakeTurnEditForm()
        list_day = day_of.objects.all()
        today = date2jalali(date.today())

        return render(request,"turn/turn.html",{'form': form,'turn':all_turns,'lsit_day':list_day,'today':today})
    else:
        return render(request, 'main/error.html',{'mess':'دسترسی ثبت نوبت برای شما فعال نشده است.'})

def take_turn_s(request, id):
    user = request.user
    x = chech_profile(user, 10)
    if x == True:
        mess =None
        all_t = Take_Turn.objects.order_by('-date_time')
        all_turns = []
        tz = pytz.timezone('Asia/Tehran')
        for i in all_t:
            if tz.localize(datetime.now())> i.date_time:
                all_turns.append(i)
            else:
                all_turns.append(i)
        if request.method == 'POST':
            print(id)
            turn_form = TakeTurnEditForm_S(request.POST)
            if turn_form.is_valid():
                AllPatient =Patient.objects.all()
                cd =turn_form.cleaned_data
                P =get_object_or_404(Patient,id=id)
                part1 = cd['part']
                d = cd['date_time']
                count = 1
                for i in all_turns:
                    d1 = i.date_time
                    if d1.date() == d.date() and part1 == i.part:
                        count += 1
                partlist = ['PM-','PK-','PH-','NM-','NK-','PH-','BM-','BK-','PG-','NG-']
                turncode = partlist[part1] + str(count)
                Take_Turn.objects.create(Patient=P,TurnCode=turncode,user=user,part=cd['part'],date_time=cd['date_time'],TypeTurn=cd['TypeTurn'],Description=cd['Description'])
                #form = TakeTurnEditForm_S()
                #patient = get_object_or_404(Patient,NationalCode=NationalCode)
                #return render(request,"turn/turn.html",{'form': form,'mess':"وقت براي بيمار رزرو شد.","patient":patient})
                mess = "وقت براي بيمار رزرو شد."

        #all_turns = Take_Turn.objects.order_by('-date_time')
        patient = get_object_or_404(Patient,id=id)
        form =TakeTurnEditForm_S()
        list_day = day_of.objects.all()
        today = date2jalali(date.today())

        return render(request,"turn/turn.html",{'form': form,"patient":patient,'mess':mess,'turn':all_turns,'lsit_day':list_day,'today':today})
    else:
        return render(request, 'main/error.html',{'mess':'دسترسی ثبت نوبت برای شما فعال نشده است.'})


def delete_turn(request, id):
    if request.method == 'POST':
        turn  =get_object_or_404(Take_Turn,id=id)
        turn.delete()
        return redirect('turn:take_turn')

def delete_turn_h(request, id):
    if request.method == 'POST':
        turn  =get_object_or_404(Take_Turn,id=id)
        turn.delete()
        return redirect('main:home')
    else:
        turn  =get_object_or_404(Take_Turn,id=id)
        pationt =turn.Patient
        turn.delete()

        return redirect(pationt)

take_turn/templates/turn/turn.html
{% extends "main/layout.html" %}
{% load static %}
{% load jalali_tags %}
{% block styles %}
<link href="{% static 'css/turn.css' %}?v=26" rel="stylesheet">
<link href="{% static 'css/Mh1PersianDatePicker.css' %}" rel="stylesheet" />
<link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
{% endblock %}
{% block content %}
<style media="screen">
.needs-validation textarea{
  height : 75px;


}
#id_date_time_0{
  display: block;
  width: 100%;
  height: calc(2.25rem + 2px);
  padding: 0.375rem 0.75rem;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5;
  color: #495057;
  background-color: #fff;
  background-clip: padding-box;
  border: 1px solid #ced4da;
  border-radius: 0.25rem;
  transition: border-color 0.15s ease-in-out,box-shadow 0.15s ease-in-out;
}
#id_date_time_1{
  display: block;
  width: 100%;
  height: calc(2.25rem + 2px);
  padding: 0.375rem 0.75rem;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5;
  color: #495057;
  background-color: #fff;
  background-clip: padding-box;
  border: 1px solid #ced4da;
  border-radius: 0.25rem;
  transition: border-color 0.15s ease-in-out,box-shadow 0.15s ease-in-out;
}
</style>
<div class="app-main__inner">
  <div class="main-card mb-3 card">
      <div class="card-body">
        {% if patient %}
       <a href="{{patient.get_absolute_url}}"><h5 class="card-title">ثبت نوبت كاربر: {{patient}}</h5></a>
          <form class="needs-validation" ction="{% url 'turn:take_turn_s' patient.NationalCode %}" method="post" novalidate>
            {% else %}
            <h5 class="card-title">ثبت نوبت</h5>
            <form class="needs-validation" action="{% url 'turn:take_turn' %}" method="post" novalidate>
              {% endif %}
              {% csrf_token %}
              <div class="form-row">
                {% if form.Patient %}
                  <div class="col-md-4 mb-3">
                      <label for="validationCustom01">كد ملي*</label>
                      {{form.Patient}}
                      <div class="valid-feedback">
                          Looks good!
                      </div>
                  </div>
                                    <div class="col-md-4 mb-3">
                      <label for="validationCustom02">نام</label>
                      {{form.First_name}}
                      <div class="valid-feedback">
                          Looks good!
                      </div>
                  </div>
                                    <div class="col-md-4 mb-3">
                      <label for="validationCustom02">نام خانوادگی</label>
                      {{form.Last_name}}
                      <div class="valid-feedback">
                          Looks good!
                      </div>
                  </div>
                                    <div class="col-md-4 mb-3">
                      <label for="validationCustom02">شماره تماس*</label>
                      {{form.mobile}}
                      <div class="valid-feedback">
                          Looks good!
                      </div>
                  </div>
                  {% endif %}

              </div>
              <div class="form-row">
                  <div class="col-md-6 mb-3">
                      <label for="validationCustom03">نوع درخواست*</label>
                      {{form.TypeTurn}}
                      <div class="invalid-feedback">
                          Please provide a valid part.
                      </div>
                  </div>
                  <div class="col-md-6 mb-3">
                      <label for="validationCustom03">بخش*</label>
                      {{form.part}}
                      <div class="invalid-feedback">
                          Please provide a valid part.
                      </div>
                  </div>
                  <div class="col-md-3 mb-3">
                      <label for="validationCustom04">تاريخ و ساعت*</label>
                      {{form.date_time}}
                      <div class="invalid-feedback">
                          Please provide a valid state.
                      </div>
                  </div>
                  <div class="col-md-3 mb-3">
                      <label for="validationCustom05">توضيحات</label>
                      {{form.Description}}
                      <div class="invalid-feedback">
                          Please!
                      </div>
                  </div>
              </div>
            <p>{{ request.user.date_joined|to_jalali:' تاریخ: 14%y/%m/%d_ ساعت: %H:%M' }}</p>
              <button class="btn btn-primary" type="submit">ثبت نوبت</button>
          </form>

      </div>
  </div>
    <div class="row">
        <div class="col-md-12">
            <div class="main-card mb-3 card">
                <div class="card-header">
                    <div class="btn-actions-pane-right">
                        <div role="group" class="btn-group-sm btn-group">
                            <button class="active btn btn-focus">ليست نوبت ها</button>
                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="align-middle mb-0 table table-borderless table-striped table-hover">
                        <thead>
                        <tr>
                            <th class="text-center">بيمار</th>
                            <th class="text-center">شماره</th>
                            <th class="text-center">خدمت</th>
                            <th class="text-center">همكار</th>
                            <th class="text-center" >تاريخ</th>
                            <th class="text-center">حذف نوبت</th>





                        </tr>
                        </thead>
                        <tbody>
                          {% for i in turn %}
                        <tr>
                                                        <td class="text-center">
                              <a href="{{i.Patient.get_absolute_url}}"><button type="button" id="PopoverCustomT-1" class="btn btn-primary btn-sm">{{i.Patient}}</button></a>

                            </td>
                                                        <td class="text-center">
                              {{i.TurnCode}}
                            </td>
                                                        <td class="text-center">
                              {% if i.part == 0 %}
                               'Post-مغز'
                              {% elif i.part == 1 %}
                                  'post-کمر'
                                {% elif i.part == 2 %}
                                 'post-هیپوفیز'
                                {% elif i.part == 3 %}
                                'new-مغز'
                                {% elif i.part == 4 %}
                                'new-کمر'
                                {% elif i.part == 5 %}
                                  'new-هیپوفیز'
                                {% elif i.part == 6 %}
                                 'بخیه-مغز'
                                {% elif i.part == 7 %}
                                  'بخیه-کمر'
                                {% endif %}
                            </td>
                            <td class="text-center">{{i.user}}</td>
                                                        <td>
                              {{i.get_jalali_date}}
                            </td>
                            <td class="text-center text-muted">
                              <form  action="{% url 'turn:delete_turn_h' i.id %}" method="post">
                                {% csrf_token %}
                                <button class="mr-2 btn-icon btn-icon-only btn btn-outline-danger" type="submit"><i class="pe-7s-trash btn-icon-wrapper"> </i></button>
                              </form>
                            </td>





                        </tr>
                      {% empty %}

                      <td class="text-center">
                          نوبتي براي امروز ثبت نشده است.
                      </td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                      {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="d-block text-center card-footer">
                  <a  href="{% url 'main:Turn_list' %}"><button class="btn-wide btn btn-success">ليست  نوبت</button></a>

                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
<script src="{% static 'js/Mh1PersianDatePicker.js' %}"></script>
<script type="text/javascript">
    window.holidays = [];
    document.getElementById('id_date_time_0').placeholder ='تاریخ 01-01-1400';
    document.getElementById('id_date_time_1').placeholder ='ساعت 10:10';
    document.getElementById('id_Description').placeholder ='توضیحات';
    document.getElementById('id_Patient').placeholder ='شماره ملی';
    document.getElementById('id_mobile').placeholder ='شماره موبایل';

</script>
{% for i in lsit_day %}
<script type="text/javascript">
  window.holidays.push('{{i.get_jalali_date}}')
</script>
{% endfor %}
<script>
    //script1
    var inputs = document.querySelectorAll('#id_date_time_0');

    for (i = 0; i < inputs.length; i++) {
        (function (i) {
          inputs[i].addEventListener('click', function () {
                Mh1PersianDatePicker.Show(this, '{{today}}', window.holidays);
            });
        })(i);
    }
    //script1
</script>
{{ form.media }}
<script type="text/javascript">id_status
  document.getElementById('id_searchtxt').placeholder ='جستجو در نوبت ها : کد ملی';
  document.getElementById('id_status').value = '4';
</script>

{% endblock %}

take_turn/templates/turn/turn2.html
{% extends "main/layout.html" %}
{% load static %}
{% load jalali_tags %}
{% block styles %}
<link href="{% static 'css/turn.css' %}?v=26" rel="stylesheet">
<link href="{% static 'css/Mh1PersianDatePicker.css' %}" rel="stylesheet" />
{% endblock %}
{% block content %}

                    <div class="app-main__inner">
                      <div class="main-card mb-3 card">
                          <div class="card-body">
                            {% if patient %}
                              <h5 class="card-title">ثبت نوبت براي پرونده : {{patient}}</h5>
                              <form class="needs-validation" action="{% url 'turn:take_turn_s' patient.NationalCode %}" method="post">
                          {% else %}
                          <h5 class="card-title">ثبت نوبت</h5>
                            <form class="needs-validation" action="{% url 'turn:take_turn' %}" method="post">
                              {% endif %}
                              {% csrf_token %}
                                  <div class="form-row">
                                    {% if form.Patient %}
                                      <div class="col-md-4 mb-3">
                                          <label for="validationCustom01">كد ملي</label>
                                          {{form.Patient}}
                                      </div>
                                      <div class="col-md-4 mb-3">
                                          <label for="validationCustom02">تلفن همراه</label>
                                          {{form.mobile}}
                                      </div>
                                      {% endif %}
                                      <div class="col-md-4 mb-3">
                                          <label for="validationCustomUsername">نوع درخواست</label>
                                          <div class="input-group">
                                              {{form.TypeTurn}}
                                          </div>
                                      </div>
                                  </div>
                                  <div class="form-row">
                                      <div class="col-md-6 mb-3">
                                          <label for="validationCustom03">بخش</label>
                                          {{form.part}}
                                      </div>
                                      <div class="col-md-3 mb-3">
                                          <label for="validationCustom04">تاريخ</label>
                                          {{form.date_time}}
                                      </div>
                                      <div class="col-md-3 mb-3">
                                          <label for="validationCustom05">توضيحات</label>
                                          {{form.Description}}
                                      </div>
                                      <p>{{ request.user.date_joined|to_jalali:' تاریخ: 14%y/%m/%d_ ساعت: %H:%M' }}</p>
                                  </div>
                                  <button class ="btn btn-primary" type="submit" name="button">ثبت</button>{% if patient %} <a  id="wbtna" href="{{patient.get_absolute_url }}"><button class ="btn btn-primary" type="button" >پرونده بيمار </button></a>{% endif %}

                              </form>


                          </div>
                      </div>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="main-card mb-3 card">
                                    <div class="card-header">
                                        <div class="btn-actions-pane-right">
                                            <div role="group" class="btn-group-sm btn-group">
                                                <button class="active btn btn-focus">ليست نوبت ها</button>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="table-responsive">
                                        <table class="align-middle mb-0 table table-borderless table-striped table-hover">
                                            <thead>
                                            <tr>
                                                <th class="text-center">حذف نوبت</th>
                                                <th>تاريخ</th>
                                                <th class="text-center">همكار</th>
                                                <th class="text-center">خدمت</th>
                                                <th class="text-center">شماره</th>
                                                <th class="text-center">بيمار</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                              {% for i in turn %}
                                            <tr>
                                                <td class="text-center text-muted">
                                                  <form  action="{% url 'turn:delete_turn_h' i.id %}" method="post">
                                                    {% csrf_token %}
                                                    <button class="mr-2 btn-icon btn-icon-only btn btn-outline-danger" type="submit"><i class="pe-7s-trash btn-icon-wrapper"> </i></button>
                                                  </form>
                                                </td>
                                                <td>
                                                  {{i.get_jalali_date}}
                                                </td>
                                                <td class="text-center">{{i.user}}</td>
                                                <td class="text-center">
                                                  {% if i.part == 0 %}
                                                   'Post-مغز'
                                                  {% elif i.part == 1 %}
                                                      'post-کمر'
                                                    {% elif i.part == 2 %}
                                                     'post-هیپوفیز'
                                                    {% elif i.part == 3 %}
                                                    'new-مغز'
                                                    {% elif i.part == 4 %}
                                                    'new-کمر'
                                                    {% elif i.part == 5 %}
                                                      'new-هیپوفیز'
                                                    {% elif i.part == 6 %}
                                                     'بخیه-مغز'
                                                    {% elif i.part == 7 %}
                                                      'بخیه-کمر'
                                                    {% endif %}
                                                </td>
                                                <td class="text-center">
                                                  {{i.TurnCode}}
                                                </td>
                                                <td class="text-center">
                                                  <a href="{{i.Patient.get_absolute_url}}"><button type="button" id="PopoverCustomT-1" class="btn btn-primary btn-sm">{{i.Patient}}</button></a>

                                                </td>
                                            </tr>
                                          {% empty %}

                                          <td class="text-center">
                                              نوبتي براي امروز ثبت نشده است.
                                          </td>
                                          <td>-</td>
                                          <td>-</td>
                                          <td>-</td>
                                          <td>-</td>
                                          <td>-</td>
                                          {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="d-block text-center card-footer">
                                      <a  href="{% url 'main:Turn_list' %}"><button class="btn-wide btn btn-success">ليست  نوبت</button></a>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
<link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
<script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
<script src="{% static 'js/Mh1PersianDatePicker.js' %}"></script>
<script type="text/javascript">
    window.holidays = [];
    document.getElementById('id_date_time_0').placeholder ='تاریخ 01-01-1400';
    document.getElementById('id_date_time_1').placeholder ='ساعت 10:10';
    document.getElementById('id_Description').placeholder ='توضیحات';
    document.getElementById('id_Patient').placeholder ='شماره ملی';
    document.getElementById('id_mobile').placeholder ='شماره موبایل';

</script>
{% for i in lsit_day %}
<script type="text/javascript">
  window.holidays.push('{{i.get_jalali_date}}')
</script>
{% endfor %}
<script>
    //script1
    var inputs = document.querySelectorAll('#id_date_time_0');

    for (i = 0; i < inputs.length; i++) {
        (function (i) {
          inputs[i].addEventListener('click', function () {
                Mh1PersianDatePicker.Show(this, '{{today}}', window.holidays);
            });
        })(i);
    }
    //script1
</script>
{{ form.media }}
<script type="text/javascript">id_status
  document.getElementById('id_searchtxt').placeholder ='جستجو در نوبت ها : کد ملی';
  document.getElementById('id_status').value = '4';
</script>

{% endblock %}